apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic3
    app.kubernetes.io/part-of: application-sample
  name: devfile-sample-go-basic3
  namespace: application-service-system
spec:
  ports:
  - port: 1111
    targetPort: 1111
  selector:
    app.kubernetes.io/instance: devfile-sample-go-basic3
status:
  loadBalancer: {}
